version: 2.1

jobs:
  build-test-release:
    docker:
      - image: cimg/python:3.9
    
    steps:
      - checkout
      
      # Installing Dependencies and creating a virtual enviornment
      - run:
          name: Install Necessary Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pyinstaller
      
      # Run tests cases
      - run:
          name: Run Test case
          command: |
            . venv/bin/activate
            pytest tests/
      
      # Build executable for python
      - run:
          name: Build Executables
          command: |
            . venv/bin/activate
            pyinstaller --onefile src/hello.py
      
      # Create GitHub Release and store executables
      - run:
          name: Create GitHub Release
          command: |
            # Install GitHub CLI if not already available
            type gh || (type curl && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
            && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y)
            
            # Create release
            RELEASE_TAG="v0.1.${CIRCLE_BUILD_NUM}"
            gh release create "$RELEASE_TAG" \
              dist/* \
              --repo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" \
              --title "Release $RELEASE_TAG" \
              --notes "Automated build from CircleCI"

workflows:
  version: 2
  build-test-release-workflow:
    jobs:
      - build-test-release:
          filters:
            branches:
              only: main